language: rust
rust:
  - nightly
sudo: false
cache: cargo

stages:
  - name: test
  - name: release
    if: tag IS present

matrix:
  include:
    - name: cargo test
      os: osx

    - name: cargo test
      os: linux

    - name: cargo test (with minimal versions)
      os: linux
      script:
        - cargo update -Zminimal-versions
        - cargo test --all --all-features

    # When updating this, the reminder to update the minimum required version in README.md.
    - name: cargo test (minimum required version)
      rust: nightly-2019-02-15

    - name: cargo clippy
      rust: nightly
      script:
        - if rustup component add clippy-preview;
          then
            cargo clippy --all -- -Dwarnings -Drust-2018-idioms;
          else
            echo 'Skipping clippy';
          fi

    - name: cargo bench
      rust: nightly
      script:
        - cargo bench --all
        - cargo bench --manifest-path futures-util/Cargo.toml --features=bench

    - name: cargo build --no-default-features
      rust: nightly
      script:
        - cargo build --manifest-path futures/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-core/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-channel/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-executor/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-io/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-sink/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-util/Cargo.toml --no-default-features

    - name: cargo build (default features)
      rust: nightly
      script:
        - cargo build --all

    - name: cargo build (compat feature)
      rust: nightly
      script:
        - cargo build --manifest-path futures/Cargo.toml --features io-compat

    - name: cargo build --target=thumbv6m-none-eabi
      rust: nightly
      install:
        - rustup target add thumbv6m-none-eabi
      script:
        - cargo run --manifest-path ci/remove-dev-dependencies/Cargo.toml */Cargo.toml
        - cargo build --manifest-path futures/Cargo.toml
            --target thumbv6m-none-eabi
            --no-default-features
            --features nightly,cfg-target-has-atomic

    - name: cargo build --target=thumbv7m-none-eabi
      rust: nightly
      install:
        - rustup target add thumbv7m-none-eabi
      script:
        - cargo run --manifest-path ci/remove-dev-dependencies/Cargo.toml */Cargo.toml
        - cargo build --manifest-path futures/Cargo.toml
            --target thumbv7m-none-eabi
            --no-default-features

    - name: cargo doc
      rust: nightly
      script:
        - cargo doc --all --no-deps --all-features

    - name: publish docs
      stage: release
      rust: nightly
      before_script:
        - echo "machine github.com login $GH_TOKEN password x-oauth-basic" >> ~/.netrc
        - chmod 0600 ~/.netrc
        - git clone https://github.com/rust-lang-nursery/futures-api-docs
      script:
        - cargo doc --all --no-deps --all-features
        - mv target/doc "futures-api-docs/$TRAVIS_TAG"
        - cd futures-api-docs
        - |
          sed -i'' -e '/<main id="doc-links">/a\
          \        <a href="https://rust-lang-nursery.github.io/futures-api-docs/'"$TRAVIS_TAG"'/futures/">\
          \          <span>'"$TRAVIS_TAG"'</span>\
          \        </a>\
          ' index.html
        - git add "$TRAVIS_TAG" index.html
        - git commit -m "Add API docs for $TRAVIS_TAG"
        - git push origin master

script:
  - cargo test --all --all-features
  - cargo test --all --all-features --release

env:
  global:
    - secure: "iwVcMVIF7ZSY82fK5UyyUvVvJxMSYrbZawh1+4Oi8pvOdYq1gptcDoOC8jxWwCwrNF1b+/85n+jlEUngEqqSmV5PjAbWPjoc+u4Zn7CRi1AlxoUlvHPiQm4vM4Mkkd6GsqoIZttCeedU9m/w0nQ18uUtK8uD6vr2FVdcMnUnkYQAxuGOowGLrwidukzfBXMCu/JrwKMIbt61knAFiI/KJknu0h1mRrhpeF/sQ3tJFzRRcQeFJkbfwDzltMpPo1hq5D3HI4ONjYi/qO2pwUhDk4umfp9cLW9MS8rQvptxJTQmWemHi+f2/U4ld6a0URL6kEuMkt/EbH0A74eFtlicfRs44dX9MlWoqbLypnC3ymqmHcpwcwNA3HmZyg800MTuU+BPK41HIPdO9tPpxjHEiqvNDknH7qs+YBnis0eH7DHJgEjXq651PjW7pm+rnHPwsj+OzKE1YBNxBQZZDkS3VnZJz+O4tVsOzc3IOz0e+lf7VVuI17C9haj117nKp3umC4MVBA0S8RfreFgqpyDeY2zwcqOr0YOlEGGRl0vyWP8Qcxx12kQ7+doLolt6Kxda4uO0hKRmIF6+qki1T+L7v8BOGOtCncz4f7IX48eQ7+Wu0OtglRn45qAa3CxjUuW6xX3KSNH66PCXV0Jtp8Ga2SSevX2wtbbFu9f+9R+PQY4="

notifications:
  email:
    on_success: never
